---
- name: Deploy app
  hosts: server
  become: yes

  tasks:
  - name: Run app in container
    command: "docker run -d -e TOKEN={{ TOKEN }} -e REDIS_HOST={{ REDIS_HOST }} -e REDIS_PASSWORD={{ REDIS_PASSWORD }} bot"
