---
- name: Install Docker, build image and Starting app
  hosts: server
  become: yes

  tasks:
  - name: Copy files to remote host
    copy:
      src: /home/ubuntu/jenkins/workspace/dev
      dest: /home/ubuntu
      owner: ubuntu
      group: ubuntu
      mode: 0644

  - name: Update apt packages
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install Docker
    apt: name=docker.io state=latest

  - name: Add user to docker group
    command: "sudo gpasswd -a $USER docker"

  - name: Build Docker image
    command: "docker build -t bot /home/ubuntu/dev/"

  - name: Run app in container
    command: "docker run -d bot -e TOKEN='{{ TOKEN }}'"
